const API_BASE='https://n8n.n8n-kokujapan.org';
const LIFF_ID='2010570929-BJxo68XQ';
let adminUid=new URLSearchParams(location.search).get('uid')||'';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>'฿'+Number(v||0).toLocaleString('th-TH',{minimumFractionDigits:2});
async function api(path){const r=await fetch(`${API_BASE}/webhook/${path}?uid=${encodeURIComponent(adminUid)}`);if(!r.ok)throw new Error(`${path}: ${r.status}`);return r.json();}
function table(headers,rows){if(!rows.length)return '<p class="muted">ไม่พบข้อมูล</p>';return `<table class="dash-table"><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table>`;}
async function load(view){const target=document.getElementById(view);target.innerHTML='<p class="muted">กำลังโหลด...</p>';try{const data=await api(`admin-${view}`);if(view==='orders')target.innerHTML=table(['เลขที่','วันที่','สถานะ','ยอดรวม','สถานะชำระเงิน'],data.orders.map(x=>`<tr><td>${esc(x.orderId)}</td><td>${esc(x.timestamp)}</td><td>${esc(x.status)}</td><td>${money(x.totalAmount)}</td><td>${esc(x.paymentStatus)}</td></tr>`));if(view==='payments')target.innerHTML=table(['เลขที่','ยอดรวม','สถานะชำระเงิน','เวลาส่งหลักฐาน'],data.payments.map(x=>`<tr><td>${esc(x.orderId)}</td><td>${money(x.totalAmount)}</td><td>${esc(x.paymentStatus)}</td><td>${esc(x.submittedAt)}</td></tr>`));if(view==='products')target.innerHTML=table(['รหัส','ชื่อ','หน่วย','ราคา','สถานะ'],data.products.map(x=>`<tr><td>${esc(x.productId)}</td><td>${esc(x.name)}</td><td>${esc(x.unit)}</td><td>${money(x.price)}</td><td>${esc(x.status)}</td></tr>`));if(view==='users')target.innerHTML=table(['LINE UID','ชื่อ','Role','สถานะเพื่อน','อัปเดตล่าสุด'],data.users.map(x=>`<tr><td>${esc(x.lineUid)}</td><td>${esc(x.displayName)}</td><td>${esc(x.role)}</td><td>${esc(x.friendStatus)}</td><td>${esc(x.updatedAt)}</td></tr>`));}catch(e){target.innerHTML=`<p class="dash-error">${esc(e.message)}</p>`;}}
async function init(){try{if(!adminUid&&window.liff){await liff.init({liffId:LIFF_ID});if(liff.isLoggedIn()){const p=await liff.getProfile();adminUid=p.userId;}}document.getElementById('who').textContent=adminUid?`LINE UID: ${adminUid}`:'กรุณาเปิดจาก LINE LIFF';load('orders');}catch(e){document.getElementById('who').textContent=e.message;}}
document.querySelectorAll('.dash-nav button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.dash-nav button,.dash-panel').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.getElementById(`panel-${btn.dataset.view}`).classList.add('active');load(btn.dataset.view);}));
init();
