'use strict';
const HISTORY_CONFIG = { LIFF_ID:'2010570929-oEaIS3oQ', N8N_BASE_URL:'https://n8n.n8n-kokujapan.org', ENDPOINT:'/webhook/get-order-history', TEST_UID:'id-001' };
const esc = (v) => String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money = (v) => `฿${Number(v || 0).toLocaleString('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const dateText = (v) => v ? new Intl.DateTimeFormat('th-TH',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)) : '-';
function closeOrBack(){ try { if (liff.isInClient()) return liff.closeWindow(); } catch {} location.href='index.html'; }
async function getUid(){ if (typeof liff==='undefined') return new URLSearchParams(location.search).get('uid')||HISTORY_CONFIG.TEST_UID; await liff.init({liffId:HISTORY_CONFIG.LIFF_ID}); if(!liff.isLoggedIn()){ liff.login(); return null; } return (await liff.getProfile()).userId; }
function badge(value){ const key=String(value||'Pending').toLowerCase().replace(/\s+/g,''); const cls=key==='approved'?'approved':key==='paid'||key==='verified'?'verified':key==='submitted'?'submitted':key==='rejected'?'rejected':'pending'; return `<span class="badge ${cls}">${esc(value||'Pending')}</span>`; }
function render(orders){ const root=document.getElementById('history-list'); if(!orders.length){ root.className='empty'; root.textContent='ยังไม่มีประวัติออเดอร์'; return; } root.className=''; root.innerHTML=orders.map(o=>`<article class="card"><div class="order-top"><div><p class="order-id">${esc(o.orderId)}</p><p class="order-date">${dateText(o.timestamp)}</p></div>${badge(o.status)}</div><p class="order-meta">สถานะการชำระเงิน: ${badge(o.paymentStatus||'รอชำระเงิน')}</p><p class="order-total">${money(o.totalAmount)}</p><div class="order-links"><a class="link ${o.pdfUrl?'':'disabled'}" href="${esc(o.pdfUrl||'#')}" target="_blank" rel="noopener">ดูใบส่งของ PDF</a>${o.paymentProofUrl?`<a class="link" href="${esc(o.paymentProofUrl)}" target="_blank" rel="noopener">ดูสลิป</a>`:''}</div></article>`).join(''); }
async function init(){ try { const uid=await getUid(); if(!uid)return; const res=await fetch(`${HISTORY_CONFIG.N8N_BASE_URL}${HISTORY_CONFIG.ENDPOINT}?uid=${encodeURIComponent(uid)}`); if(!res.ok)throw new Error(`โหลดข้อมูลไม่สำเร็จ (${res.status})`); const body=await res.json(); render(Array.isArray(body.orders)?body.orders:[]); } catch(e){ const root=document.getElementById('history-list'); root.className='empty'; root.textContent=e.message; } }
document.addEventListener('DOMContentLoaded',init);
