'use strict';
const PAYMENT_CONFIG = { LIFF_ID:'2010570929-oEaIS3oQ', N8N_BASE_URL:'https://n8n.n8n-kokujapan.org', HISTORY:'/webhook/get-order-history', SUBMIT:'/webhook/submit-payment-proof', TEST_UID:'id-001', MAX_FILE_BYTES:5*1024*1024 };
let currentUid=''; let selectableOrders=[];
const money=(v)=>`฿${Number(v||0).toLocaleString('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
function closeOrBack(){ try { if(liff.isInClient()) return liff.closeWindow(); }catch{} location.href='index.html'; }
function show(kind,text){ const el=document.getElementById('message'); el.className=`message ${kind}`; el.textContent=text; }
function clearMessage(){ const el=document.getElementById('message'); el.className='message'; el.textContent=''; }
async function getUid(){ if(typeof liff==='undefined')return new URLSearchParams(location.search).get('uid')||PAYMENT_CONFIG.TEST_UID; await liff.init({liffId:PAYMENT_CONFIG.LIFF_ID}); if(!liff.isLoggedIn()){liff.login();return null;} return (await liff.getProfile()).userId; }
function allowed(order){ const payment=String(order.paymentStatusRaw || order.paymentStatus || '').trim().toLowerCase(); return String(order.status||'').toLowerCase()==='approved' && !['submitted','verified','paid','????????????????????','????????????','?????????????????????????'].includes(payment); }
async function loadOrders(){ const res=await fetch(`${PAYMENT_CONFIG.N8N_BASE_URL}${PAYMENT_CONFIG.HISTORY}?uid=${encodeURIComponent(currentUid)}`); if(!res.ok)throw new Error(`โหลดรายการไม่สำเร็จ (${res.status})`); const data=await res.json(); selectableOrders=(data.orders||[]).filter(allowed); const select=document.getElementById('order-id'); select.innerHTML='<option value="">เลือกออเดอร์ที่อนุมัติแล้ว</option>'+selectableOrders.map(o=>`<option value="${o.orderId}">${o.orderId} · ${money(o.totalAmount)}</option>`).join(''); if(!selectableOrders.length)show('error','ยังไม่มีออเดอร์ที่อนุมัติและรอการส่งหลักฐาน'); }
function toDataUrl(file){ return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=()=>reject(new Error('อ่านไฟล์ไม่สำเร็จ'));r.onload=()=>resolve(String(r.result));r.readAsDataURL(file);}); }
document.addEventListener('DOMContentLoaded',async()=>{ document.getElementById('transfer-at').value=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16); document.getElementById('proof-file').addEventListener('change',async e=>{ clearMessage(); const f=e.target.files?.[0]; const p=document.getElementById('proof-preview'); if(!f){p.style.display='none';return;} if(f.size>PAYMENT_CONFIG.MAX_FILE_BYTES){show('error','รูปสลิปมีขนาดเกิน 5 MB');e.target.value='';p.style.display='none';return;} p.src=await toDataUrl(f);p.style.display='block'; }); try { currentUid=await getUid(); if(currentUid)await loadOrders(); }catch(e){show('error',e.message);} document.getElementById('payment-form').addEventListener('submit',async e=>{e.preventDefault();clearMessage();const file=document.getElementById('proof-file').files?.[0];const orderId=document.getElementById('order-id').value;if(!file||!orderId)return show('error','กรุณาเลือกออเดอร์และแนบสลิป');const btn=document.getElementById('submit-payment');btn.disabled=true;btn.textContent='กำลังส่งหลักฐาน...';try{const payload={lineUid:currentUid,orderId,transferAt:new Date(document.getElementById('transfer-at').value).toISOString(),amount:Number(document.getElementById('payment-amount').value),note:document.getElementById('payment-note').value.trim(),proofDataUrl:await toDataUrl(file),proofFileName:file.name};const res=await fetch(`${PAYMENT_CONFIG.N8N_BASE_URL}${PAYMENT_CONFIG.SUBMIT}`,{method:'POST',headers:{'Content-Type':'text/plain;charset=UTF-8'},body:JSON.stringify(payload)});const body=await res.json();if(!res.ok||!body.success)throw new Error(body.message||'ส่งหลักฐานไม่สำเร็จ');show('success','ส่งหลักฐานการโอนเงินแล้ว ทีมงานจะตรวจสอบโดยเร็ว');e.target.reset();document.getElementById('proof-preview').style.display='none';await loadOrders();}catch(err){show('error',err.message);}finally{btn.disabled=false;btn.textContent='ส่งหลักฐานการโอนเงิน';}}); });
